<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitCrew.Dashboard.Features.Images\PitCrew.Dashboard.Features.Images.csproj" />
    <ProjectReference Include="..\PitCrew.Dashboard.Kernel.Authentication\PitCrew.Dashboard.Kernel.Authentication.csproj" />
    <ProjectReference Include="..\PitCrew.Dashboard.WebApi\PitCrew.Dashboard.WebApi.csproj" />
  </ItemGroup>

</Project>
