<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NeedlrAutoGenerate>false</NeedlrAutoGenerate>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitCrew.Support.Canary.AppHost\PitCrew.Support.Canary.AppHost.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Canary.Contracts\PitCrew.Support.Canary.Contracts.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Canary.Runner\PitCrew.Support.Canary.Runner.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Canary.Scenarios\PitCrew.Support.Canary.Scenarios.csproj" />
  </ItemGroup>

</Project>
