<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NeedlrAutoGenerate>false</NeedlrAutoGenerate>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitCrew.Support.Canary.Contracts\PitCrew.Support.Canary.Contracts.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Canary.Scenarios\PitCrew.Support.Canary.Scenarios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>PitCrew.Support.Canary.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
