namespace PitCrew.Connector.Features.Sync;

/// <summary>
/// Describes the locally observed rollout state of one profile.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="ManifestSourcePath"/> is the current static-profile manifest
/// source path (from <c>root.manifest.sourcePath</c>) that Setup-Runner must
/// consume with <c>-ProfilePath</c> to preserve the currently applied
/// configuration; it is always locally generated by the connector and never
/// received from Dashboard.
/// </para>
/// <para>
/// Local routing values are read from the current desired-capacity document
/// and are required so <see cref="ImageRolloutCommandExecutor"/> can build a
/// Setup-Runner invocation that preserves the current scope/routing/capacity
/// without requiring Dashboard to send any of them on the wire.
/// </para>
/// </remarks>
internal sealed record ImageRolloutProfileState(
    string ProfileId,
    string Architecture,
    string? CurrentImageReference,
    string? CurrentImageDigest,
    string? CurrentLocalImageId,
    string? CurrentWorkerRevision,
    string StaticFingerprint,
    string PreservedConfigurationFingerprint,
    string RoutingFingerprint,
    int DesiredGeneration,
    string? DesiredStateHash,
    int ObservedStateAgeSeconds,
    string ManagerConvergenceStatus,
    int? CurrentWorkers,
    int? StaleWorkers,
    bool LocalSchemaSupported,
    string? LocalFailureCategory,
    string StaticProfileJson,
    string? ManifestSourcePath,
    string? NamePrefix,
    ImageRolloutRoutingState Routing);
