<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <NeedlrAutoGenerate>false</NeedlrAutoGenerate>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitCrew.Support.Protocol\PitCrew.Support.Protocol.csproj" />
  </ItemGroup>

</Project>
