<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NeedlrAutoGenerate>false</NeedlrAutoGenerate>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitCrew.Dashboard.Features.Access\PitCrew.Dashboard.Features.Access.csproj" />
    <ProjectReference Include="..\PitCrew.Dashboard.Features.Support\PitCrew.Dashboard.Features.Support.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Canary.Contracts\PitCrew.Support.Canary.Contracts.csproj" />
    <ProjectReference Include="..\PitCrew.Support.Protocol\PitCrew.Support.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>PitCrew.Support.Canary.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
